---
- name: Get Facts
  hosts: all
  gather_facts: false
  tasks:
    - name: Get minimum facts and display version
      arista.eos.eos_facts:
        gather_subset:
          - min
      register: facts
      debug:
        msg: "{{facts.ansible_facts.ansible_net_hostname}} - EOS Version {{facts.ansible_facts.ansible_net_version}}."
